version: '3.8'

services:
  pdf-to-html-service:
    build: .
    container_name: pdf-to-html-service
    ports:
      - "5050:5000"
    volumes:
      - ./outputs:/tmp/outputs
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - PUBLIC_BASE_URL=https://docs.149-130-164-187.sslip.io
      - PUBLIC_ASSET_TTL_SECONDS=3600
    restart: unless-stopped
